export const COACHING_MODULES = [
  {
    id: 'coaching-1',
    number: 1,
    title: 'The Consultant Mindset',
    icon: '🧠',
    teaser: 'From transactional to relational thinking',
    bullets: [
      'Moving from transactional to relational thinking',
      "Understanding the property practitioner's world",
      'First impressions and personal positioning',
      'Building trust before asking for business',
    ],
  },
  {
    id: 'coaching-2',
    number: 2,
    title: 'Understanding the Property Practitioner',
    icon: '🤝',
    teaser: 'What agents actually need from you',
    bullets: [
      'What property practitioners actually need from consultants',
      'Pain points in deals, communication, and clients',
      'Becoming easy to work with',
      'Aligning your service with their success',
    ],
  },
  {
    id: 'coaching-3',
    number: 3,
    title: 'Building a Powerful Personal Brand',
    icon: '⭐',
    teaser: '"A brand called you" in the lending space',
    bullets: [
      '"A brand called you" in the lending space',
      'Professional presence (online and offline)',
      'Consistency and credibility',
      'Becoming memorable',
    ],
  },
  {
    id: 'coaching-4',
    number: 4,
    title: 'Communication Mastery',
    icon: '💬',
    teaser: 'Speed, structure, and difficult conversations',
    bullets: [
      'Speed vs quality of communication',
      'Structuring updates to property practitioners',
      'Managing expectations',
      'Difficult conversations',
    ],
  },
  {
    id: 'coaching-5',
    number: 5,
    title: 'Creating Value Beyond the Bond',
    icon: '💡',
    teaser: 'Be the expert, not just the originator',
    bullets: [
      'Educating property practitioners and clients',
      'Market insights and guidance',
      'Being a problem solver',
      'Value-add conversations',
    ],
  },
  {
    id: 'coaching-6',
    number: 6,
    title: 'Referral Growth Systems',
    icon: '🔁',
    teaser: 'Turn one deal into five',
    bullets: [
      'How referrals actually work',
      'Building a referral pipeline',
      'Asking without asking',
      'Turning one deal into five',
    ],
  },
  {
    id: 'coaching-7',
    number: 7,
    title: "Leveraging BetterBond's Ecosystem",
    icon: '🛠️',
    teaser: 'Tools, services, and smart cross-selling',
    bullets: [
      'Using Private Property effectively',
      'Using Loom for communication',
      'Positioning Nurture and other services',
      'Cross-selling without being pushy',
    ],
  },
  {
    id: 'coaching-8',
    number: 8,
    title: 'Client Experience Excellence',
    icon: '🌟',
    teaser: 'Create advocates, not just clients',
    bullets: [
      'Creating memorable client journeys',
      'Managing buyers emotionally',
      'Turning clients into advocates',
      'Post-bond follow-up strategies',
    ],
  },
  {
    id: 'coaching-9',
    number: 9,
    title: 'Time, Energy & Pipeline Management',
    icon: '⚡',
    teaser: 'Structure your week for peak performance',
    bullets: [
      'Structuring a high-performance week',
      'Managing multiple deals',
      'Avoiding burnout',
      'Consistent activity vs reactive work',
    ],
  },
  {
    id: 'coaching-10',
    number: 10,
    title: 'Handling Objections & Resistance',
    icon: '🛡️',
    teaser: 'Confidence and clarity in every response',
    bullets: [
      'Objections from property practitioners',
      'Objections from buyers',
      'Confidence and clarity in responses',
      'Reframing objections',
    ],
  },
  {
    id: 'coaching-11',
    number: 11,
    title: 'Long-Term Relationship Building',
    icon: '🏆',
    teaser: 'Stay relevant long after the deal closes',
    bullets: [
      'Staying relevant after the deal',
      'CRM habits and touches',
      'Becoming the "go-to" consultant',
      'Building a network, not a database',
    ],
  },
  {
    id: 'coaching-12',
    number: 12,
    title: 'Becoming a Market Leader',
    icon: '👑',
    teaser: 'Thought leadership and strategic growth',
    bullets: [
      'Thought leadership',
      'Community presence',
      'Strategic partnerships',
      'Scaling your business sustainably',
    ],
  },
]
